apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-test
  namespace: coder
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: "bitbull/webserver"
        ports:
        - containerPort: 80
